import { Challenge } from '../model';

export const INITIAL_CHALLENGES: Challenge[] = [
  // Rey
  {
    id: 'c-rey-1',
    archetypeId: 'rey',
    title: 'Definir las tres prioridades de la semana',
    description: 'Poner orden en tu mundo empezando por delimitar con claridad lo esencial de lo secundario.',
    actionGuidance: 'Escribe en tu libreta o notas las 3 únicas metas prioritarias que determinarán el éxito de tu semana y desestima el resto.',
    timeEstimate: '15 min',
    difficulty: 'accesible',
    completed: false,
  },
  {
    id: 'c-rey-2',
    archetypeId: 'rey',
    title: 'Acto explícito de reconocimiento',
    description: 'Como soberano consciente, bendice y valida el talento o esfuerzo de un miembro de tu equipo o familia.',
    actionGuidance: 'Comunica a alguien de tu entorno un elogio genuino y específico sobre su contribución sin esperar retribución.',
    timeEstimate: '10 min',
    difficulty: 'accesible',
    completed: false,
  },
  {
    id: 'c-rey-3',
    archetypeId: 'rey',
    title: 'Asumir una decisión postergada',
    description: 'Cerrar una indecisión que genera caos o incertidumbre en tu entorno.',
    actionGuidance: 'Analiza pros y contras de esa decisión que vienes aplazando, elige el rumbo y comunícalo con serenidad.',
    timeEstimate: '30 min',
    difficulty: 'profundo',
    completed: false,
  },

  // Guerrero
  {
    id: 'c-guerrero-1',
    archetypeId: 'guerrero',
    title: 'Completar la tarea incómoda primero',
    description: 'Encarar la tarea más pesada del día en los primeros 60 minutos sin postergaciones.',
    actionGuidance: 'Identifica la actividad que más fricción te genera y ejecútala de principio a fin antes de revisar redes o correos triviales.',
    timeEstimate: '45 min',
    difficulty: 'intermedio',
    completed: false,
  },
  {
    id: 'c-guerrero-2',
    archetypeId: 'guerrero',
    title: 'Fijar un límite claro y sin disculpas',
    description: 'Decir un "no" firme y respetuoso a un compromiso que compromete tu integridad o descanso.',
    actionGuidance: 'Declina una petición que no desees asumir con una frase breve, cortés y sin dar excusas innecesarias.',
    timeEstimate: '5 min',
    difficulty: 'accesible',
    completed: false,
  },
  {
    id: 'c-guerrero-3',
    archetypeId: 'guerrero',
    title: 'Sesión de esfuerzo físico con presencia',
    description: 'Entrenar la disciplina corporal y la tolerancia a la incomodidad.',
    actionGuidance: 'Realiza 30 minutos de ejercicio físico intenso, concentrándote en tu respiración y en mantener la postura.',
    timeEstimate: '30 min',
    difficulty: 'intermedio',
    completed: false,
  },

  // Mago
  {
    id: 'c-mago-1',
    archetypeId: 'mago',
    title: 'Investigación de patrones subyacentes',
    description: 'Analizar un problema recurrente y descubrir las 3 variables invisibles que lo sostienen.',
    actionGuidance: 'Elige un conflicto o traba habitual y escribe en una hoja: "¿Qué dinámica invisible estoy alimentando sin darme cuenta?".',
    timeEstimate: '20 min',
    difficulty: 'intermedio',
    completed: false,
  },
  {
    id: 'c-mago-2',
    archetypeId: 'mago',
    title: 'Traducción de lo complejo a lo simple',
    description: 'Sintetizar un concepto abstracto para que cualquier persona pueda comprenderlo y aplicarlo.',
    actionGuidance: 'Explica a alguien o escribe una analogía sencilla que resuma un principio complejo que dominas.',
    timeEstimate: '15 min',
    difficulty: 'accesible',
    completed: false,
  },

  // Amante
  {
    id: 'c-amante-1',
    archetypeId: 'amante',
    title: 'Presencia sensorial plena de 30 minutos',
    description: 'Conectar profundamente con algo que amas sin pantallas ni distracciones.',
    actionGuidance: 'Dedica media hora a escuchar música con ojos cerrados, contemplar un paisaje natural o preparar una comida con devoción.',
    timeEstimate: '30 min',
    difficulty: 'accesible',
    completed: false,
  },
  {
    id: 'c-amante-2',
    archetypeId: 'amante',
    title: 'Expresión de aprecio sin filtros',
    description: 'Abrir el corazón para manifestar afecto sincero y admiración a alguien especial.',
    actionGuidance: 'Envía una nota honesta o dile a alguien cercano qué es lo que más valoras de su presencia en tu vida.',
    timeEstimate: '10 min',
    difficulty: 'intermedio',
    completed: false,
  },

  // Padre
  {
    id: 'c-padre-1',
    archetypeId: 'padre',
    title: 'Espacio de mentoría generosa',
    description: 'Dedicar tiempo a guiar y enseñar a alguien con menos experiencia.',
    actionGuidance: 'Comparte un aprendizaje clave o enseña una destreza práctica a alguien que lo necesite, escuchando sus inquietudes.',
    timeEstimate: '40 min',
    difficulty: 'intermedio',
    completed: false,
  },
  {
    id: 'c-padre-2',
    archetypeId: 'padre',
    title: 'Redactar tu carta de valores esenciales',
    description: 'Definir el legado moral y las lecciones de vida que deseas transmitir.',
    actionGuidance: 'Escribe los 5 principios no negociables que guían tus decisiones y que te gustaría que perduren en tu entorno.',
    timeEstimate: '25 min',
    difficulty: 'profundo',
    completed: false,
  },

  // Cuidador
  {
    id: 'c-cuidador-1',
    archetypeId: 'cuidador',
    title: 'Servicio discreto y anónimo',
    description: 'Realizar un acto de bondad o ayuda tangible sin buscar reconocimiento.',
    actionGuidance: 'Haz una labor de cuidado o facilita una tarea pesada a alguien sin dejar rastro de que fuiste tú quien lo hizo.',
    timeEstimate: '20 min',
    difficulty: 'accesible',
    completed: false,
  },
  {
    id: 'c-cuidador-2',
    archetypeId: 'cuidador',
    title: 'Pausa de autocuidado no negociable',
    description: 'Cuidar al cuidador: recargar tu propia vasija antes de seguir sirviendo a otros.',
    actionGuidance: 'Regálate 45 minutos de reposo, masaje, baño relajante o lectura tranquila sin sentir culpa.',
    timeEstimate: '45 min',
    difficulty: 'accesible',
    completed: false,
  },

  // Bufón
  {
    id: 'c-bufon-1',
    archetypeId: 'bufon',
    title: 'Desdramatizar un problema con humor',
    description: 'Quitarle solemnidad y dramatismo a una preocupación cotidiana.',
    actionGuidance: 'Escribe un monólogo cómico o exagera con ironía divertida tus preocupaciones actuales hasta sonreír.',
    timeEstimate: '15 min',
    difficulty: 'accesible',
    completed: false,
  },
  {
    id: 'c-bufon-2',
    archetypeId: 'bufon',
    title: 'Momento de juego e improvisación pura',
    description: 'Conectar con la espontaneidad sin preocuparse por la productividad.',
    actionGuidance: 'Participa en un juego con amigos, baila sin coreografía o improvisa una escena divertida sin juicio.',
    timeEstimate: '20 min',
    difficulty: 'accesible',
    completed: false,
  },

  // Explorador
  {
    id: 'c-explorador-1',
    archetypeId: 'explorador',
    title: 'Micro-expedición fuera de ruta',
    description: 'Romper la monotonía y explorar un lugar o disciplina fuera de tu radar habitual.',
    actionGuidance: 'Camina por un barrio desconocido, prueba un restaurante de comida extranjera que nunca hayas probado o lee un ensayo atípico.',
    timeEstimate: '60 min',
    difficulty: 'intermedio',
    completed: false,
  },
  {
    id: 'c-explorador-2',
    archetypeId: 'explorador',
    title: 'Cuestionar un dogma personal',
    description: 'Aventurarse a pensar más allá de los límites de tu propia mentalidad.',
    actionGuidance: 'Identifica una certeza fija sobre tu identidad y pregúntate: "¿Y si lo contrario también tuviera algo de verdad?".',
    timeEstimate: '20 min',
    difficulty: 'profundo',
    completed: false,
  },

  // Creador
  {
    id: 'c-creador-1',
    archetypeId: 'creador',
    title: 'Construir algo pequeño y terminarlo hoy',
    description: 'Vencer el perfeccionismo cerrando un ciclo creativo completo en una sola sesión.',
    actionGuidance: 'Escribe un poema breve, programa un script, pinta un boceto o crea un objeto y decláralo terminado hoy.',
    timeEstimate: '45 min',
    difficulty: 'intermedio',
    completed: false,
  },
  {
    id: 'c-creador-2',
    archetypeId: 'creador',
    title: 'Lluvia de 10 ideas no convencionales',
    description: 'Entrenar el músculo de la imaginación divergente sin censura previa.',
    actionGuidance: 'Apunta 10 ideas locas o innovadoras para mejorar un aspecto de tu vida o trabajo en menos de 10 minutos.',
    timeEstimate: '10 min',
    difficulty: 'accesible',
    completed: false,
  },

  // Sabio
  {
    id: 'c-sabio-1',
    archetypeId: 'sabio',
    title: 'El ejercicio del abogado del diablo',
    description: 'Buscar argumentos sólidos que contradigan una convicción personal arraigada.',
    actionGuidance: 'Elige una postura política, social o profesional que defiendas y escribe 3 razones legítimas por las que el bando opuesto piensa como piensa.',
    timeEstimate: '25 min',
    difficulty: 'profundo',
    completed: false,
  },
  {
    id: 'c-sabio-2',
    archetypeId: 'sabio',
    title: 'Diario de 15 minutos de silencio contemplativo',
    description: 'Permanecer en silencio absoluto observando tus propios pensamientos sin reaccionar.',
    actionGuidance: 'Siéntate en silencio sin teléfono ni música y al terminar anota qué claridad emergió del reposo mental.',
    timeEstimate: '20 min',
    difficulty: 'intermedio',
    completed: false,
  },

  // Héroe
  {
    id: 'c-heroe-1',
    archetypeId: 'heroe',
    title: 'Cruzar el umbral del miedo',
    description: 'Hacer una acción constructiva que te intimide de manera directa.',
    actionGuidance: 'Haz esa llamada difícil, pide el aumento o postúlate a esa oportunidad que has temido encarar.',
    timeEstimate: '20 min',
    difficulty: 'profundo',
    completed: false,
  },
  {
    id: 'c-heroe-2',
    archetypeId: 'heroe',
    title: 'Reencuadre de la caída',
    description: 'Extraer oro de un tropiezo pasado transformando la queja en fuerza.',
    actionGuidance: 'Escribe sobre un error o fracaso reciente y redacta 3 aprendizajes de acero que te hacen más sabio hoy.',
    timeEstimate: '20 min',
    difficulty: 'intermedio',
    completed: false,
  },

  // Rebelde
  {
    id: 'c-rebelde-1',
    archetypeId: 'rebelde',
    title: 'Desafiar un mandato heredado obsoleto',
    description: 'Cuestionar una regla tácita o tradición que ya no sirve a tu crecimiento.',
    actionGuidance: 'Identifica una expectativa externa que cargas por inercia y decide conscientemente soltarla esta semana.',
    timeEstimate: '25 min',
    difficulty: 'intermedio',
    completed: false,
  },
  {
    id: 'c-rebelde-2',
    archetypeId: 'rebelde',
    title: 'Propuesta de innovación disruptiva',
    description: 'Proponer una mejora radical para un proceso burocrático o desgastado.',
    actionGuidance: 'Presenta una alternativa constructiva y fresca para solucionar un cuello de botella en tu trabajo o dinámica personal.',
    timeEstimate: '30 min',
    difficulty: 'profundo',
    completed: false,
  }
];
